apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e2e-tests-nodejs-jsbzdpir
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-nodejs-jsbzdpir 
  name: e2e-tests-nodejs-jsbzdpir
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: e2e-tests-nodejs-jsbzdpir 
